[build]
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  included_files = ["data/embeddings.json"] # Include the pre-computed embeddings file

[functions.chatbot]
  memory = 1024
  timeout = 10

[functions.enhance-prompt]
  memory = 128

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200