[build]
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@xenova/transformers"]
  included_files = ["data/knowledge_base.txt"]

[functions.chatbot]
  memory = 1536
  timeout = 60
  node_options = ["--expose-gc"]
  environment = { TRANSFORMERS_CACHE = "/tmp", TORCH_HOME = "/tmp" }

[functions.enhance-prompt]
  memory = 128

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200