[build]
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@xenova/transformers"]
  included_files = ["data/knowledge_base.txt", "netlify/functions/embeddings_cache.json"]

[functions.chatbot]
  memory = 1024
  timeout = 10
  environment = { 
    TRANSFORMERS_CACHE = "/tmp",
    TORCH_HOME = "/tmp",
    DISABLE_SHARP = "true",
    USE_ONNX = "1"
  }

[functions.enhance-prompt]
  memory = 128

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200