[build]
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@xenova/transformers"]
  included_files = ["data/knowledge_base.txt"]
  
[functions.chatbot]
  memory = 3008
  timeout = 30

[functions.enhance-prompt]
  memory = 128

[build.environment]
  NODE_VERSION = "18"
  TRANSFORMERS_CACHE = "/tmp/transformers"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200