# netlify.toml

[build] 
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  # Common settings for all Netlify Functions
  node_bundler = "esbuild"
  included_files = ["data/embeddings.json"]

  # Specific configuration for your existing functions
  [functions.chatbot] 
    memory = 1536
    timeout = 30

  [functions.enhance-prompt] 
    memory = 128
    timeout = 30

# Scheduled function for fetching news and events daily
[[functions]]
  function = "fetch-news"
  schedule = "0 23 * * *"

# Scheduled function for cleaning up old data monthly
[[functions]]
  function = "cleanup-archive"
  schedule = "0 23 28-31 * *"
  
[build.environment]
  NODE_VERSION = "20" 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200